version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/test-circleci

    steps:
      - checkout:
          path: ~/test-circleci

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sudo chmod 777 ./gradlew
      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew test
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run: ls -a
      - run: docker image build -t spring-docker-demo:0.0.1 ./
      - run: docker run -it -p 8080:8080 spring-docker-demo:0.0.1
      - run: curl -X GET http://localhost:8080/
